### ISSUE TITLE
the run time is 150ms/frame in CPU? 

### ISSUE THREAD

**Issue by tzhang2014** [zeusees/FaceBoxes#1]

**Comment by lsy17096535** [comment]
@tzhang2014  single thread , multithread will less than 50ms per frame.

**Comment by luuuyi** [comment]
@lsy17096535 which part can use multithread to optimize? CNN part?

**Comment by tzhang2014** [comment]
the run time is 320ms in my PC, i7 , CPU , os is ubuntu16.04,

**Comment by JackyWang0001** [comment]
I also test the demo, and the fps only 1. My OS is win7(i3-4160 cpu 3.6GHz). Now i doubt the runing speed as you say.

**Comment by lsy17096535** [comment]
@JackyWang0001  #12  He got 50-60ms, the speed related to your machine.

**Comment by JackyWang0001** [comment]
@lsy17096535 I test the mtcnn face detector on my machine, and get the fps about 15. Both use the same the camera (640*480).

**Comment by lsy17096535** [comment]
@Jacky3213  More details you can ask faceboxes author. https://github.com/sfzhang15
we just reimplement the algorithm.
