### ISSUE TITLE
"caffe.LayerParameter" has no field named "permute_param".

### ISSUE THREAD

**Issue by alex17sh** [zeusees/FaceBoxes#11]
Hi,
I receive the following message:
"caffe.LayerParameter" has no field named "permute_param".
I saw the threads:
#4 and #10 
I also use the caffe-ssd version from here:
https://github.com/weiliu89/caffe/tree/ssd
but I still encounter the problem, any ideas?
Thanks!

**Comment by lsy17096535** [comment]
I think you have adopt wrong caffe version. Check again.

**Comment by ArthurSea** [comment]
hi, Which caffe version used, please paste a link， thanks

**Comment by fengpingbaustem** [comment]
@ArthurSea caffe ssd should be ok, I met the same issue, make sure the PYTHONPATH has correctly set.
