### ISSUE TITLE
face confidence

### ISSUE THREAD

**Issue by zhanglaplace** [zeusees/FaceBoxes#12]
Hi, thank you for you nice code

why the confidence could bigger than 1.0

i test the video average speed is 50-60ms

**Comment by lsy17096535** [comment]
@zhanglaplace  confidence is relate to train mothed. The speed was test on my laptop.

**Comment by zhanglaplace** [comment]
@lsy17096535  i test the confidence closing 5.0 , i want to know the how high the score mean the face is reliably

**Comment by unaplugin** [comment]
hi, I test on my PC with the confidences bigger than 1.0 too.
Anyone could deal with it?
