### ISSUE TITLE
Train the model

### ISSUE THREAD

**Issue by Jacky3213** [zeusees/FaceBoxes#13]
Hello sir, thanks for your contribution. Recently i am interested in the FaceBoxes, as it is so fast with a high accuracy. According to your network files，i train the model with modyfing the prior_box layer. Now i complete the training with a bad result. Wihtout a loss decline, the model detects no face. I have been confused about it for several days. Looking forward to your reply.

**Comment by lsy17096535** [comment]
@Jacky3213  Faceboxes is not good for small face. Training faceboxes have some tricks, include data prepare and parameter select. we do not get the accuracy and speed as well as the author. for more details you have to ask the author.
