### ISSUE TITLE
low accuracy

### ISSUE THREAD

**Issue by qianwenjun0801** [zeusees/FaceBoxes#14]
i check the model and method using real-time video, and the  accuracy of each frame is too low...maybe should retrain the model. could you show the parameters and datasets of your models so that we can do something right to update the accuracy.

**Comment by ezetl** [comment]
Hello, Is the model `FaceBoxes_1024x1024.caffemodel` the final model? Im having a hard time trying to surpass accuracy 0.9. Should I retrain?
