### ISSUE TITLE
为什么c++不能调用呢？

### ISSUE THREAD

**Issue by how0723** [zeusees/FaceBoxes#16]
为什么c++不能调用呢？
运行Mat detections = net.forward() 显示如下错误
OpenCV(3.4.1) Error: Assertion failed ((numPriors * _numLocClasses * 4) == inputs[0][1]) in cv::dnn::DetectionOutputLayerImpl::getMemoryShapes, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\layers\detection_output_layer.cpp, line 208

**Comment by lsy17096535** [comment]
看一下自己输入的图片是否正确
