### ISSUE TITLE
ubuntu14.04+caffe+cpu can't use||  caffe version different???

### ISSUE THREAD

**Issue by jiagh2010** [zeusees/FaceBoxes#17]
W0426 22:16:29.791591  3547 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0426 22:16:29.791712  3547 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0426 22:16:29.791738  3547 _caffe.cpp:125] Net('faceboxes_deploy.prototxt', 1, weights='FaceBoxes_1024x1024.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 1818:17: Message type "caffe.LayerParameter" has no field named "permute_param".
F0426 22:16:29.795361  3547 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: faceboxes_deploy.prototxt
*** Check failure stack trace: ***

**Comment by lsy17096535** [comment]
caffe版本不对，采用caffe-ssd。

**Comment by Xu-jingjing** [comment]
我也碰到了和你相同的问题，麻烦问一下你是怎么解决的，多谢 @lauhsu
