### ISSUE TITLE
fixed_ratio and aspect_ratio

### ISSUE THREAD

**Issue by lxg2015** [zeusees/FaceBoxes#18]
在致密化anchor的代码里，fixed_ratio、fixed_size和原priorbox层的aspect_ratio、min_size的功能应该是一样的吧？请问为什么要重复定义这样的变量呢？

**Comment by lsy17096535** [comment]
这是实现时候的一些问题，当时实现的过程没有考虑这么多，为了尽快完成代码，o(*￣︶￣*)o
