### ISSUE TITLE
怎么在windows上测试

### ISSUE THREAD

**Issue by andeyeluguo** [zeusees/FaceBoxes#19]
怎么移植到windows上测试呢

**Comment by lsy17096535** [comment]
在window的caffe版本中修改对应的代码即可使用

**Comment by lsy17096535** [comment]
@qq2891018428  用这个，https://github.com/zeusees/FaceBoxes/blob/master/examples/faceboxes/demo/faceboxes_image.py

**Comment by jnulzl** [comment]
@andeyeluguo将该仓库中的Pribox层替换win caffe ssd中的就可以测试了

**Comment by andeyeluguo** [comment]
@jnulzl 阁下是用的哪个版本的windows-caffe

**Comment by qq2891018428** [comment]
@lsy17096535 不会派森呀。 所以我都是用C++写的，233333. 用你的那个demo目录下面的caffemodel测试，结果最后都是输出 -inf， 说明float溢出了。我还在找原因是什么

**Comment by qq2891018428** [comment]
@andeyeluguo 他都告诉你了是ssd那个。。。。。

**Comment by lsy17096535** [comment]
@qq2891018428  以前有c++的测试代码，我找一下，还在的话发给你。

**Comment by andeyeluguo** [comment]
有直接的ssd版本呀？我用微软的把ssd的层加进去各种报错。。。 @qq2891018428 @jnulzl

**Comment by qq2891018428** [comment]
@andeyeluguo 我自己有一个微软的caffe版本。 然后，我直接把整个工程，复制替换。修改了部分代码就OK了，可惜，结果貌似不对。 有一部分代码，需要手动修改的。很少，找个正常可以windows跑起来的caffe，照着改改就好了

**Comment by KevinZhang1201** [comment]
@qq2891018428 我在windows 上测试 caffemodel 结果也全是 -inf，你已经找到这个问题了吗？
