### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by Grabber** [zeusees/FaceBoxes#2]
will the training code be available?

**Comment by lsy17096535** [comment]
@Grabber  You can produce imdb dataset and train your own model based on caffe-ssd framework. 
https://github.com/weiliu89/caffe/tree/ssd

**Comment by Grabber** [comment]
@lsy17096535, sent a message on QQ, need to talk with you. Are you on now?

**Comment by lsy17096535** [comment]
@Grabber tell me your QQ number
