### ISSUE TITLE
bad performance when I changed the shape of input from 1024 to 300

### ISSUE THREAD

**Issue by peyer** [zeusees/FaceBoxes#20]
@zryfish Thanks for your re-implementation of FaceBoxes. I found that with your provided caffemodel (1024 * 1024), the time used for the forward of model with python interface(pycaffe) is about 0.4s, so I just want to reshape the input size to 300 or 512.
What I want to know is that  if the  cost time will less that 0.04s even using cpp interface. If I want to run real-timely, should I change the shape of input from 1024 to 300 like?
Take 300 as an instance, I modified the stride used for detection to 8, 16, 32, and changed the fixed_size to  small than 300. After trained 12000 iterations, the final caffemodel works badly on FDDB or just a simple image with number of face less than  10  and no occlusion .
What should I do next?

**Comment by lsy17096535** [comment]
faceboxes algorithm is baesd on ssd structure， so it is more time consuming than mtcnn. we recommend you to use mtcnn to get less time cost.
