### ISSUE TITLE
INFERENCE SPEED

### ISSUE THREAD

**Issue by laycoding** [zeusees/FaceBoxes#25]
Hi~
        Have you test the inference speed on GPU machine? I run the demo script on my P4 machine, but don't reproduce the result in paper.

**Comment by lsy17096535** [comment]
we also can not reproduce the result

**Comment by laycoding** [comment]
Sad, I get 60ms/p on P4 which is about 7 times slower than 125fps in paper. Have you ask the authors if they did any quantization or distillation?

**Comment by lsy17096535** [comment]
the network architecture is slow, you can ask the author how to get high forward speed.

**Comment by laycoding** [comment]
3ks for sharing～～
