### ISSUE TITLE
the results on the FDDB

### ISSUE THREAD

**Issue by coder-james** [zeusees/FaceBoxes#3]
The reproduced results on the FDDB are bad, do you use fewer epochs or another datasets?
 when i  reproduced that paper according to https://github.com/lqs19881030/faceboxes, 
I find the training procedure was slow because of the large input image. Have you try smaller input images, like 512 x 512?

**Comment by lsy17096535** [comment]
@coder-james  Yep, the training procedure was slow. @tfygg  He had tried 512*512 , performance is  better on small faces.

**Comment by Brilliaoce** [comment]
I have test your model on FDDB dataset, but I can't get the results showed on your website. 
![discroc2](https://user-images.githubusercontent.com/5762997/32039918-921623f2-ba61-11e7-8613-e707bad42fa5.jpg)
I don't know why it's so different with your DiscROC curve.

**Comment by Brilliaoce** [comment]
![discroc2](https://user-images.githubusercontent.com/5762997/32040082-1454d962-ba62-11e7-95dd-7167fc7b7760.jpg)

**Comment by lsy17096535** [comment]
@Brilliaoce  The model we provide has been trained 60000 ite, so if you want get better results, you can train based on out model.
