### ISSUE TITLE
Error1google/protobuf/port_def

### ISSUE THREAD

**Issue by zihaozhang9** [zeusees/FaceBoxes#42]
您好！我使用如下命令编译时
`make -j8`
会产生报错：
log：
`compilation terminated.
make: *** [.build_release/src/caffe/data_reader.o] Error 1
In file included from ./include/caffe/util/cudnn.hpp:8:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layer.cpp:2:
.build_release/src/caffe/proto/caffe.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
`
貌似是找不到那个文件。应该怎么弄呢。

**Comment by lsy17096535** [comment]
编译 protobuf

**Comment by zihaozhang9** [comment]
> 编译 protobuf

是的，我已经按照教程[csdn](https://blog.csdn.net/xiangxianghehe/article/details/78928629)编译protobuf，但是仍然不行。我应该怎么操作。怎么验证我的protobuf编译成功。需要把protobuf的路径加入到CMakeList.txt里面吗

**Comment by lsy17096535** [comment]
你查一下caffe的编译安装方式的教程，普通的caffe编译没有问题之后，直接编译这个。

**Comment by zihaozhang9** [comment]
> 你查一下caffe的编译安装方式的教程，普通的caffe编译没有问题之后，直接编译这个。

恩，非常感谢。我发现可能是caffe的问题。为了图方便，我是conda 安装的caffe。

**Comment by lsy17096535** [comment]
不行，用faceboxes必须自己编译这个repo里面提供的caffe代码

**Comment by zihaozhang9** [comment]
我已经编译安装了caffe。我测试import caffe时已经成功了。
我想测试一下效果，
我修改了[faceboxes_image.py](https://github.com/zeusees/FaceBoxes/blob/master/examples/faceboxes/demo/faceboxes_image.py#L10)变为`net_file= 'faceboxes_deploy.prototxt'`。存放了几张图片。但是得到报错：
`[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 1760:19: Message type "caffe.LayerParameter" has no field named "prior_box_param".
F0721 13:40:11.278558 21147 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: faceboxes_deploy.prototxt
*** Check failure stack trace: ***
已放弃 (核心已转储)`
是prototxt的问题吗

**Comment by lsy17096535** [comment]
你编译的caffe不是这个git中提供的，你的是原始caffe，没有ssd的prior_box layer,重新试一下。

**Comment by zihaozhang9** [comment]
嗯！是这样的。我已经重新编译了此库中的caffe，已经成功运行。我想测试一下caffe版本和pytorch版本会不会有速度上的不同。我用caffe的gpu才6帧，cpu才3帧。而pytorch版本的gpu可以到30帧，cpu有10帧。相同设备，用摄像头读取视频测试。这是为什么呢？我以为caffe框架效率会更好，不会吗？

**Comment by lsy17096535** [comment]
caffe的很多layer实现都是原始方式，没有很多的考虑效率跟速度，但是思路清晰。很多新的框架进行了针对不同设备，平台的优化，有速度优势。

**Comment by zihaozhang9** [comment]
这两个版本用的模型应该是一样的呀。我下载了win版本的exe，感觉也是流畅的。是视频每帧都处理了吗。

**Comment by zihaozhang9** [comment]
> caffe的很多layer实现都是原始方式，没有很多的考虑效率跟速度，但是思路清晰。很多新的框架进行了针对不同设备，平台的优化，有速度优势。

了解了。感谢您的回复。那论文中如果用pytorch框架实验，是不是速度更快，那得到的速度结果会更好。win的exe没有做优化吗。如果做成exe是只能用caffe框架了吗。如果用pytorch最后怎么能变成exe，它可以在vs上编写吗

**Comment by Francoforever** [comment]
楼主，我也是“为了图方便，conda 安装的caffe”，求问你最后解决了嘛？

**Comment by Francoforever** [comment]
楼主，我也是“为了图方便，conda安装的caffe”。求问你最后怎么解决的啊？

**Comment by zihaozhang9** [comment]
> 楼主，我也是“为了图方便，conda安装的caffe”。求问你最后怎么解决的啊？

conda安装的caffe在环境变量里面没有设置路径，而且安装的资源可能会少。还是建议用caffe源码编译安装。安装过程中可能会出现很多问题，依赖项版本不对什么的，耐心解决一下就好了。一定要设置正确的环境变量。上次安装的过程我已经忘记了，但是自己记录了笔记，你可以参考下[ubuntu18.04, cuda10 anaconda编译安装caffe](https://blog.csdn.net/firing00/article/details/96732745)
[ubuntu下载编译安装protobuf](https://blog.csdn.net/firing00/article/details/95008254)

**Comment by Francoforever** [comment]
> > 楼主，我也是“为了图方便，conda安装的caffe”。求问你最后怎么解决的啊？
> 
> conda安装的caffe在环境变量里面没有设置路径，而且安装的资源可能会少。还是建议用caffe源码编译安装。安装过程中可能会出现很多问题，依赖项版本不对什么的，耐心解决一下就好了。一定要设置正确的环境变量。上次安装的过程我已经忘记了，但是自己记录了笔记，你可以参考下[ubuntu18.04, cuda10 anaconda编译安装caffe](https://blog.csdn.net/firing00/article/details/96732745)
> [ubuntu下载编译安装protobuf](https://blog.csdn.net/firing00/article/details/95008254)

太感谢了！！还想问一句，楼主你这个方法安装的caffe还是会缺少ssd一些自有layer的吧？比如permute等等。

**Comment by zihaozhang9** [comment]
> > > 楼主，我也是“为了图方便，conda安装的caffe”。求问你最后怎么解决的啊？
> > 
> > 
> > conda安装的caffe在环境变量里面没有设置路径，而且安装的资源可能会少。还是建议用caffe源码编译安装。安装过程中可能会出现很多问题，依赖项版本不对什么的，耐心解决一下就好了。一定要设置正确的环境变量。上次安装的过程我已经忘记了，但是自己记录了笔记，你可以参考下[ubuntu18.04, cuda10 anaconda编译安装caffe](https://blog.csdn.net/firing00/article/details/96732745)
> > [ubuntu下载编译安装protobuf](https://blog.csdn.net/firing00/article/details/95008254)
> 
> 太感谢了！！还想问一句，楼主你这个方法安装的caffe还是会缺少ssd一些自有layer的吧？比如permute等等。

ssd?我运行FaceBoxes时好像没啥问题的
