### ISSUE TITLE
ERROR cuda_runtime.h:1

### ISSUE THREAD

**Issue by zihaozhang9** [zeusees/FaceBoxes#43]
cuda-10.0
很奇怪我用相同的配置，编译官方[caffe](https://github.com/BVLC/caffe)时没有任何报错。
但是编译本github库中的caffe时会得到如下错误
`NVCC src/caffe/solvers/adagrad_solver.cu
In file included from /usr/local/cuda-10.0/include/cuda_runtime.h:120:0,
                 from <command-line>:0:
/home/nnir712/anaconda3/envs/facebox/include/boost/config/compiler/nvcc.hpp:22:34: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #if !defined(__CUDACC_VER__) || (__CUDACC_VER__ < 70500)
                                  ^
In file included from /usr/local/cuda-10.0/include/cuda_runtime.h:120:0,
                 from <command-line>:0:
/home/nnir712/anaconda3/envs/facebox/include/boost/config/compiler/nvcc.hpp:22:34: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #if !defined(__CUDACC_VER__) || (__CUDACC_VER__ < 70500)
                                  ^
In file included from /usr/local/cuda-10.0/include/cuda_runtime.h:120:0,
                 from <command-line>:0:
/home/nnir712/anaconda3/envs/facebox/include/boost/config/compiler/nvcc.hpp:22:34: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #if !defined(__CUDACC_VER__) || (__CUDACC_VER__ < 70500)
                                  ^
Makefile:588: recipe for target '.build_release/cuda/src/caffe/solvers/nesterov_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/nesterov_solver.o] Error 1
make: *** 正在等待未完成的任务....
Makefile:588: recipe for target '.build_release/cuda/src/caffe/solvers/sgd_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/sgd_solver.o] Error 1
Makefile:588: recipe for target '.build_release/cuda/src/caffe/solvers/adagrad_solver.o' failed
make: *** [.build_release/cuda/src/caffe/solvers/adagrad_solver.o] Error 1
`

**Comment by zihaozhang9** [comment]
是boost版本的问题，已解决[#163](https://github.com/astra-toolbox/astra-toolbox/issues/163)。

**Comment by lsy17096535** [comment]
ok
