### ISSUE TITLE
我发现你的deploy.prototxt并没有做anchor的稠密化？

### ISSUE THREAD

**Issue by KeyKy** [zeusees/FaceBoxes#9]
我发现你的deploy.prototxt并没有做anchor的稠密化？ 我修改了一下根据你之前的一个github，但是我发现我训不出来，请问你加了稠密化后能不能训出来？

**Comment by lsy17096535** [comment]
@KeyKy  需要修改对应的源码，我自己caffe训练到91左右，我用别人mxnet写的，能到93

**Comment by KeyKy** [comment]
@lsy17096535 你有pretrained模型能分享吗？我就是按你的另个github的源码改的，能否分享一下solver，我的loss一直在8~9 徘徊不下。

**Comment by liyuanyaun** [comment]
我也是损失一直不下降，不太懂是什么问题？求指教

**Comment by liyuanyaun** [comment]
我也是损失一直不下降，不太懂是什么问题？求指教 @KeyKy @lsy17096535

**Comment by lsy17096535** [comment]
这个版本没有做稠密化，因为涉及到修改caffe源码，可以看一下我个人的github，里面有对应的修改代码。

**Comment by jnulzl** [comment]
@lsy17096535 你指的修改caffe源码是修改“prior_box_layer”吗？？

**Comment by jnulzl** [comment]
@lsy17096535 请问稠密化后效果能提高多少？？

**Comment by lsy17096535** [comment]
@jnulzl 能做到91%左右，作者的精度是在fddb放大三倍的情况下测得的。

**Comment by jnulzl** [comment]
@lsy17096535 嗯嗯，我看作者的训练数据做了各种数据扩增，你训练时数据扩增了吗
